spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: taco_cloud
  data:
    rest:
      base-path: /data-api

  security:
    user:
      name: user
      password: 123
server:
  port: 8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

taco:
  orders:
    page-size: 10
#
#logging:
#  file:
#    path: /var/logs/
#    name: TacoCloud.log
#  level:
#    root: warn
#    org:
#      springframework:
#        security: debug
#